name:                functory
version:             0.1.0.0
github:              "forestaa/functory"
license:             BSD3
author:              "Morita Daichi"
maintainer:          "t.daichi.3@gmail.com"
copyright:           "2019 Morita Daichi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/forestaa/functory#readme>

dependencies:
- base >= 4.7 && < 5
- extensible
- mtl
- rio

default-extensions:
- DataKinds
- DerivingVia
- KindSignatures
- FlexibleContexts
- LambdaCase
- NoImplicitPrelude
- OverloadedLabels
- StandaloneDeriving
- Strict
- StrictData
- TypeApplications
- TypeFamilyDependencies
- TypeOperators

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-unticked-promoted-constructors



executables:
  functory-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - functory

tests:
  functory-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - functory
    - hspec
